[versions]
loom = "1.15.+"

minecraft = "26.1.2"

# https://fabricmc.net/develop
fabric-loader = "0.18.6"
fabric-api = "0.145.4+26.1.2"

# dev env mods
# https://modrinth.com/mod/sodium/versions?l=fabric
sodium = "mc26.1.1-0.8.9-fabric"
# https://modrinth.com/mod/modmenu/versions
mod_menu = "18.0.0-alpha.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
mod-menu = { module = "maven.modrinth:modmenu", version.ref = "mod_menu" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
dev = [ "sodium", "mod-menu"]

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
