name: build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type of build
        required: true
        options:
          - normal
          - snapshot
          - release
        default: normal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        # note: setup-gradle v6+ has switched to a proprietary license.
        # pin this to v5 for the foreseeable future.
        # https://blog.gradle.org/github-actions-for-gradle-v6
        uses: gradle/actions/setup-gradle@v5
        with:
          validate-wrappers: true

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew runGametest

      - name: Publish Snapshot
        if: ${{ github.event.inputs.type == 'snapshot' }}
        run: >-
          ./gradlew publishAllPublicationsToDevOsSnapshotsRepository
          -PdevOsSnapshotsUsername="${{ secrets.MAVEN_USER }}"
          -PdevOsSnapshotsPassword="${{ secrets.MAVEN_PASS }}"

      - name: Publish Release
        if: ${{ github.event.inputs.type == 'release' }}
        run: >-
          ./gradlew publishAllPublicationsToDevOsReleasesRepository
          -PdevOsReleasesUsername="${{ secrets.MAVEN_USER }}"
          -PdevOsReleasesPassword="${{ secrets.MAVEN_PASS }}"

      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
